"""empty message

Revision ID: 1c63661e76d9
Revises: 416e0e751478
Create Date: 2015-12-28 23:22:23.113000

"""

# revision identifiers, used by Alembic.
revision = '1c63661e76d9'
down_revision = '416e0e751478'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
