"""empty message

Revision ID: 27649840bde6
Revises: 298b282f3f0e
Create Date: 2015-08-26 22:40:29.037000

"""

# revision identifiers, used by Alembic.
revision = '27649840bde6'
down_revision = '298b282f3f0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
