"""empty message

Revision ID: 416e0e751478
Revises: 1328d8c404c5
Create Date: 2015-12-28 23:15:03.251000

"""

# revision identifiers, used by Alembic.
revision = '416e0e751478'
down_revision = '1328d8c404c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
