"""empty message

Revision ID: 4382357ccbee
Revises: 449787b36699
Create Date: 2015-12-28 23:48:40.110000

"""

# revision identifiers, used by Alembic.
revision = '4382357ccbee'
down_revision = '449787b36699'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
