"""empty message

Revision ID: 449787b36699
Revises: 1c63661e76d9
Create Date: 2015-12-28 23:23:55.986000

"""

# revision identifiers, used by Alembic.
revision = '449787b36699'
down_revision = '1c63661e76d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
