"""empty message

Revision ID: 4aa0043d2006
Revises: 3b5afa881660
Create Date: 2015-12-29 20:30:18.105000

"""

# revision identifiers, used by Alembic.
revision = '4aa0043d2006'
down_revision = '3b5afa881660'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
